_BASE_: "Base-RCNN-FPN.yaml"
OUTPUT_DIR: "./Mixed/integratedImageNet/output"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 14 
  RETINANET:
    NUM_CLASSES: 14
  SEM_SEG_HEAD:
    NUM_CLASSES: 14
DATASETS:
  DLA:
    REGISTER_NEW_DATASET: True
    TRAIN:
      NAME: "Mixed_train"
      JSON: "./datasets/Mixed/train/annotations/train_annotations.json"
      PATH: "./datasets/Mixed/train/"
    TEST:
      NAME: "Mixed_test"
      JSON: "./datasets/Mixed/test/annotations/test_annotations.json"
      PATH: "./datasets/Mixed/test/"
  TEST:
  - Mixed_test
  TRAIN:
  - Mixed_train
