_BASE_: "Base-RCNN-FPN.yaml"
OUTPUT_DIR: "../../../VORAU/integrated_ImageNet/output/"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 4
  RETINANET:
    NUM_CLASSES: 4
  SEM_SEG_HEAD:
    NUM_CLASSES: 4
DATASETS:
  DLA:
    REGISTER_NEW_DATASET: True
    TRAIN:
      NAME: "VORAU_train"
      JSON: "../../../../../datasets/VORAU/train_all/annotations/train_annotations.json"
      PATH: "../../../../../datasets/VORAU/train_all/"
    TEST:
      NAME: "VORAU_test"
      JSON: "../../../../../datasets/VORAU/test/annotations/test_annotations.json"
      PATH: "../../../../../datasets/VORAU/test/"
  TEST:
  - VORAU_test
  TRAIN:
  - VORAU_train
